#                                                               ADS LAB ASSIGNMENT I

*Name:*     Sanidhya \
*SID:*    22106024 \
*Branch:* Computer Science Engineering (Data Science)

In [1]:
import numpy as np

In [2]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
array1.shape

(3, 3)

## Solution 1

In [4]:
height , width = array1.shape
new_height = height + 2
new_width = width + 2

top_border = np.zeros((1, width))
bottom_border = np.zeros((1, width))
left_border = np.zeros((new_height, 1))
right_border = np.zeros((new_height, 1))

new_arr = np.concatenate((top_border, array1, bottom_border), axis=0)
new_arr = np.concatenate((left_border, new_arr, right_border), axis=1 )

In [5]:
new_arr

array([[0., 0., 0., 0., 0.],
       [0., 1., 2., 3., 0.],
       [0., 4., 5., 6., 0.],
       [0., 7., 8., 9., 0.],
       [0., 0., 0., 0., 0.]])

## Solution 2

In [6]:
array2 = np.random.random((5,5))
array2

array([[0.49888846, 0.59644542, 0.72398498, 0.5099553 , 0.32067926],
       [0.85587473, 0.20418263, 0.57639349, 0.26455587, 0.79887719],
       [0.53157842, 0.04034752, 0.49607088, 0.01561915, 0.1279949 ],
       [0.02275901, 0.10890915, 0.07683792, 0.73697624, 0.80409858],
       [0.68420925, 0.768534  , 0.39997065, 0.40035049, 0.83240305]])

## Solution 3

In [7]:
array3 = np.random.randint(low = -50 , high = 50 , size = (10,2))
array3

array([[ 38,  36],
       [-38, -28],
       [  1, -13],
       [-50, -13],
       [-34, -42],
       [-21,  15],
       [-29,   6],
       [-43, -30],
       [ 19, -10],
       [-45, -24]])

In [8]:
def convert(array):
    temp = []
    for i in range(len(array)):
        x , y = tuple(array[i])
        r = np.sqrt((x**2) + (y**2))
        theta = np.arctan(y/x)
        temp.append([r , theta])
    return temp

In [9]:
show = convert(array3)
show

[[52.3450093132096, 0.7583777142101835],
 [47.20169488482379, 0.6350267353903137],
 [13.038404810405298, -1.4940244355251187],
 [51.66236541235796, 0.25436805855326594],
 [54.037024344425184, 0.8902751021276822],
 [25.80697580112788, -0.6202494859828215],
 [29.614185789921695, -0.20401797959254858],
 [52.43090691567332, 0.6091634656607725],
 [21.470910553583888, -0.4844779290370232],
 [51.0, 0.4899573262537283]]

## Solution 4

In [10]:
array4 = np.random.randint(low = -50 , high = 50 , size = (10,10))
array4

array([[-28,  25, -30,  27, -14,  15,  25,   3, -29, -48],
       [-18, -31,  39,   5,  37, -36,  19,  -4,  48,  -3],
       [  8,  23, -15,  -5,  -1, -47,  16,  -5,  21, -34],
       [ 28,  40,  16, -39,  16,  11,   5,  -7,  40,  47],
       [ -4, -21,  -8,   6, -37, -29,   7, -33, -13, -47],
       [ -1,  -8,  44, -48,  31,  -9,  -9, -43,  35, -16],
       [ 39,  -4,  13,  45,  -6, -43,   6, -28,  33,  47],
       [-15, -12, -33, -40,  11, -18,   6, -12, -13, -42],
       [ -5,   5, -48,  26,  38,  10, -43, -31,  26,  49],
       [ 29, -49,  31,   3, -30,   8,  44,  29, -36,  41]])

In [11]:
temp = []
for i in range(len(array4)-2):
    for j in range(len(array4)-2):
        
        temp.append(array4[[i,i+1 , i+2]][:,[j,j+1,j+2]])

In [12]:
temp

[array([[-28,  25, -30],
        [-18, -31,  39],
        [  8,  23, -15]]),
 array([[ 25, -30,  27],
        [-31,  39,   5],
        [ 23, -15,  -5]]),
 array([[-30,  27, -14],
        [ 39,   5,  37],
        [-15,  -5,  -1]]),
 array([[ 27, -14,  15],
        [  5,  37, -36],
        [ -5,  -1, -47]]),
 array([[-14,  15,  25],
        [ 37, -36,  19],
        [ -1, -47,  16]]),
 array([[ 15,  25,   3],
        [-36,  19,  -4],
        [-47,  16,  -5]]),
 array([[ 25,   3, -29],
        [ 19,  -4,  48],
        [ 16,  -5,  21]]),
 array([[  3, -29, -48],
        [ -4,  48,  -3],
        [ -5,  21, -34]]),
 array([[-18, -31,  39],
        [  8,  23, -15],
        [ 28,  40,  16]]),
 array([[-31,  39,   5],
        [ 23, -15,  -5],
        [ 40,  16, -39]]),
 array([[ 39,   5,  37],
        [-15,  -5,  -1],
        [ 16, -39,  16]]),
 array([[  5,  37, -36],
        [ -5,  -1, -47],
        [-39,  16,  11]]),
 array([[ 37, -36,  19],
        [ -1, -47,  16],
        [ 16,  11,   5]]),

## Solution 5

In [13]:
len(temp)

64

In [14]:
def block_sum(array):
    temp = []
    temp2 = []
    for arr in array:
        temp.append(sum(arr))
    for arr in temp:
        temp2.append(sum(arr))
    return temp2

In [15]:
temp2 = np.array(block_sum(temp))

In [16]:
temp2

array([ -27,   38,   43,  -19,   14,  -14,   94,  -51,   90,   33,   53,
        -59,   20,  -48,  133,  103,   67,   -3,  -67, -125,  -59,  -82,
         31,  -31,   86,  -18,  -19,  -98,  -14, -107,  -18,  -37,   50,
         19,   40,  -90,  -89, -181,  -45,  -65,   23,  -43,   17,  -77,
        -31, -150,  -25,  -39,  -60,  -48,    6,   23,  -39, -153,  -56,
         29,  -97, -117,  -42,    8,   26,   -7,  -30,   11])

## Solution 6

In [17]:
array5 = np.random.randint(size = (10,3) , low = -50 , high = 50)
array5

array([[ 42,  41,  45],
       [ 31,   4, -36],
       [-19,   9, -41],
       [ 45,  -2,  39],
       [ -1, -16,   2],
       [ -2,  19, -11],
       [-14, -17,  11],
       [-47, -19, -13],
       [ 43,  -3, -43],
       [ 25, -22,  23]])

In [18]:
def equal_rows(array):
    unequal_rows = array[np.any(array, axis=1)]
    return unequal_rows

In [19]:
ans = equal_rows(array5)
ans

array([[ 42,  41,  45],
       [ 31,   4, -36],
       [-19,   9, -41],
       [ 45,  -2,  39],
       [ -1, -16,   2],
       [ -2,  19, -11],
       [-14, -17,  11],
       [-47, -19, -13],
       [ 43,  -3, -43],
       [ 25, -22,  23]])

## Solution 7

In [20]:
temp_arr = [23.4,3,55534,56,546,54,76,765,7,6,46,546,5,65,564,64,5,3]
temp = []
for ele in temp_arr:
    if ele < 10:
        temp.append(10)
    elif ele > 30:
        temp.append(30)
    else:
        temp.append(ele)

In [21]:
temp

[23.4, 10, 30, 30, 30, 30, 30, 30, 10, 10, 30, 30, 10, 30, 30, 30, 10, 10]

In [22]:
print(np.argmax(temp_arr))

2


## Solution 8

In [23]:
def max_index(array):
    temp = array
    for i in range(5):
        print(np.argmax(temp))
        temp.pop(np.argmax(temp))

In [24]:
max_index(temp_arr)

2
6
12
3
8


## Solution 9

In [25]:
array6 = np.random.randint(high = 50 , low = -50 , size = (10,10))
array6

array([[-22,  44, -38,   2,   8, -50, -12, -17,  20,  36],
       [ 22, -30,  47,  17, -39, -35, -50, -42,  38, -19],
       [-24, -50,  47, -11,  13, -38, -43,   4,  29,  23],
       [ 29, -45, -34,  21,  23,  27,  -4, -36,  21,  48],
       [ 13,  27,  -6,  39,  21, -25, -12,   3,  23,  14],
       [ 27, -12,  14,  39,  35, -15,  35,  -3, -48, -42],
       [ 33,   6,  46, -33,  22,  46, -13,   3, -40, -17],
       [ 32,   6,  45, -37, -25,  43, -33,  -9,  41,  38],
       [-11, -41,  30, -43,  18, -32,  13,  23,  14, -13],
       [ 36,  38,   7,  28,  19,  -9, -44,  14,  -4, -50]])

In [26]:
def unique_count(array):
    temp  = []
    for i in range(len(array)):
        temp.append(len(set(array[i])))
    return temp

In [27]:
ans = unique_count(array6)
ans

[10, 10, 10, 9, 10, 9, 9, 10, 10, 10]

## Solution 10

In [28]:
def find_duplicates(arr):
    seen = np.zeros_like(arr)
    return (arr >= seen) & (seen != 0)

In [29]:
array_7 = [1,1,1,2,3,4,5,5,5,6,7,8]
find_duplicates(array_7)

array([False, False, False, False, False, False, False, False, False,
       False, False, False])

## Solution 11

In [30]:
import matplotlib.pyplot as plt
%matplotlib inline
from pathlib import Path
from PIL import Image
import warnings
warnings.filterwarnings("ignore")

In [31]:
img_path = Path("F:\independence.jpg")
img = Image.open(img_path)
img_arr = np.asarray(img)
img_arr

array([[[ 64,  69, 135],
        [ 64,  90, 123],
        [ 67,  98, 129],
        ...,
        [152, 181, 195],
        [150, 182, 195],
        [167, 176, 193]],

       [[ 65,  68, 145],
        [ 58,  81, 131],
        [ 66,  87, 144],
        ...,
        [164, 195, 200],
        [160, 173, 189],
        [159, 181, 194]],

       [[ 61,  78, 130],
        [ 66,  74, 123],
        [ 68,  83, 122],
        ...,
        [167, 193, 192],
        [171, 184, 193],
        [155, 177, 191]],

       ...,

       [[ 23,  42,  72],
        [ 20,  37,  65],
        [ 23,  38,  67],
        ...,
        [ 89, 124, 162],
        [ 91, 122, 166],
        [ 83, 115, 162]],

       [[ 24,  48,  74],
        [ 24,  44,  71],
        [ 25,  42,  68],
        ...,
        [ 80, 129, 169],
        [ 87, 129, 179],
        [ 86, 110, 170]],

       [[ 19,  45,  70],
        [ 23,  44,  71],
        [ 22,  42,  67],
        ...,
        [ 65, 124, 166],
        [ 79, 128, 186],
        [ 87, 107, 180]]

## Solution 12

In [32]:
def find_peaks(arr):
    temp = []
    for i in range(1,len(arr)-1):
        if (arr[i] > arr[i-1]) and (arr[i] > arr[i+1]):
            temp.append(arr[i])
    return temp

In [33]:
array_8 = [1,2,1,3,5,2]
ans = find_peaks(array_8)
ans

[2, 5]

## Solution 13

In [34]:
import pandas as pd

In [35]:
def date_range(arr):
    dates = pd.to_datetime(arr)
    min_date = dates.min()
    max_date = dates.max()
    date_range = pd.date_range(start=min_date, end=max_date, freq="D")
    missing_dates = date_range.difference(dates)
    dates = dates.append(missing_dates)
    dates = dates.sort_values()
    return dates

In [36]:
array_dates = ["2023-01-01", "2023-01-03", "2023-01-05", "2023-01-08"]
ans = date_range(array_dates)
ans

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08'],
              dtype='datetime64[ns]', freq=None)

## Solution 14

In [37]:
def stride(arr):
    temp = []
    for i in range(len(arr)-3):
        temp.append([arr[i] , arr[i+1] , arr[i+2] , arr[i+3]])
    return temp

In [38]:
array_9 = [1,2,3,4,5,6,7,8,9,10]
ans = stride(array_9)
ans

[[1, 2, 3, 4],
 [2, 3, 4, 5],
 [3, 4, 5, 6],
 [4, 5, 6, 7],
 [5, 6, 7, 8],
 [6, 7, 8, 9],
 [7, 8, 9, 10]]

## Solution 15

In [39]:
def avg_stride(arr):
    temp = []
    for i in range(len(arr)-2):
        avg = (arr[i] + arr[i+1] + arr[i+2])/3
        temp.append(avg)
    return temp

In [40]:
ans = avg_stride(array_9)
ans

[2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]